version: "2"
services:
  api:
    build: .
    container_name: api
    volumes:
      - ".:/var/www/"
      - "./public:/var/www/html"
    ports:
      - "7177:80"
  mysql:
      container_name: mysql
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dbname
      ports:
        - "3306:3306"
      volumes:
        - mysqldata:/var/lib/mysql
volumes:
  mysqldata: